--SELECT 'grant select on ' || table_name || ' to PLANIMETRICS_READONLY ;' FROM user_tables
--WHERE table_name NOT LIKE '%$'

grant select on BOARDWALK to PLANIMETRICS_READONLY ;
grant select on UPDATED_LINE to PLANIMETRICS_READONLY ;
grant select on UPDATED_POINT to PLANIMETRICS_READONLY ;
grant select on UPDATED_POLYGON to PLANIMETRICS_READONLY ;
grant select on RAILROAD_STRUCTURE to PLANIMETRICS_READONLY ;
grant select on RETAININGWALL to PLANIMETRICS_READONLY ;
grant select on ROADBED to PLANIMETRICS_READONLY ;
grant select on SHORELINE to PLANIMETRICS_READONLY ;
grant select on SIDEWALK to PLANIMETRICS_READONLY ;
grant select on SIDEWALK_LINE to PLANIMETRICS_READONLY ;
grant select on STREET_FURNITURE_POINT to PLANIMETRICS_READONLY ;
grant select on MEDIAN to PLANIMETRICS_READONLY ;
grant select on MISC_STRUCTURE_POLY to PLANIMETRICS_READONLY ;
grant select on OPEN_SPACE_NO_PARK to PLANIMETRICS_READONLY ;
grant select on COOLING_TOWERS to PLANIMETRICS_READONLY ;
grant select on CURB to PLANIMETRICS_READONLY ;
grant select on DELETED_LINE to PLANIMETRICS_READONLY ;
grant select on DELETED_POINT to PLANIMETRICS_READONLY ;
grant select on DELETED_POLYGON to PLANIMETRICS_READONLY ;
grant select on ELEVATION to PLANIMETRICS_READONLY ;
grant select on HYDRO_STRUCTURE to PLANIMETRICS_READONLY ;
grant select on HYDROGRAPHY to PLANIMETRICS_READONLY ;
grant select on STREET_FURNITURE_POLY to PLANIMETRICS_READONLY ;
grant select on SWIMMING_POOL to PLANIMETRICS_READONLY ;
grant select on TRANSPORT_STRUCTURE to PLANIMETRICS_READONLY ;
grant select on UNDER_CONSTRUCTION_UNKNOWN to PLANIMETRICS_READONLY ;
grant select on PARK to PLANIMETRICS_READONLY ;
grant select on PARKING_LOT to PLANIMETRICS_READONLY ;
grant select on PAVEMENT_EDGE to PLANIMETRICS_READONLY ;
grant select on PLAZA to PLANIMETRICS_READONLY ;
grant select on RAILROAD to PLANIMETRICS_READONLY ;
